---
title: ''
output: html_document
---

```{r include = FALSE}
require(knitr)
opts_knit$set(root.dir=normalizePath('../'))
knitr::opts_chunk$set(echo = FALSE, fig.align='center', fig.pos = 'H', message = FALSE, warning = FALSE)
options(knitr.kable.NA = '')
```

```{r}
load("data/preproc_data.RData")
source('helpers/helpers.R')
source('helpers/settings.R')
```

### Bias 

```{r, results = 'asis'}
groupedSubjSes <- data %>%
  group_by(session, subject) %>%
  nest() %>%
  mutate(JV10e = map(.x = data, .f = ~bays_2009_error(X = .x$fourier_R, Tg = .x$S_rad))) %>%
  mutate(JV10 = map(.x = data, .f = ~bays_2009_fit(X = .x$fourier_R, Tg = .x$S_rad, return.ll = TRUE))) %>%
  mutate(precision = map_dbl(JV10e, 1), 
         bias = map_dbl(JV10e, 2),
         L = unlist(map(.x = JV10, .f = ~.x$LL)),
         K = unlist(map(.x = JV10, .f = ~.x$B['K'])),
         Pt = unlist(map(.x = JV10, .f = ~.x$B['Pt'])),
         Pu = unlist(map(.x = JV10, .f = ~.x$B['Pu'])),
         sd = k2sd(K),
         precision_mixture = 1/sd,
         n = unlist(map(.x = data, .f = ~nrow(.x))),
         group = substr(subject, 1,1), 
         time = unlist(map(data, function(x) unique(x['time'])))) 
# relevel
groupedSubjSes$group <- factor(groupedSubjSes$group, levels = c('E', 'C', 'S'))
groupedData <- data %>%
  group_by(group, session) %>%
  nest() %>%
  mutate(JV10e = map(.x = data, .f = ~bays_2009_error(X = .x$fourier_R, Tg = .x$S_rad))) %>%
  mutate(JV10 = map(.x = data, .f = ~bays_2009_fit(X = .x$fourier_R, Tg = .x$S_rad, return.ll = TRUE))) %>%
  mutate(precision = map_dbl(JV10e, 1), 
         bias = map_dbl(JV10e, 2),
         L = unlist(map(.x = JV10, .f = ~.x$LL)),
         K = unlist(map(.x = JV10, .f = ~.x$B['K'])),
         Pt = unlist(map(.x = JV10, .f = ~.x$B['Pt'])),
         Pu = unlist(map(.x = JV10, .f = ~.x$B['Pu'])),
         sd = k2sd(K),
         precision_mixture = 1/sd,
         time = unlist(map(data, function(x) unique(x['time'])))) 
```


```{r, results = 'asis', eval = FALSE}
aux <- unlist(lapply(levels(data$session), function(x) setNames(2,x)))
aux0 <- apply(expand.grid(c("precision", "bias"), levels(data$session)), 
              1, paste, collapse=".")
aux1 <- apply(expand.grid(c("precision", "bias"), levels(data$session)), 
              1, paste, collapse=".")
groupedData %>%
  select(group, session, precision, bias) %>%
  as.data.frame() %>%
  reshape(idvar = 'group', timevar = 'session', direction = "wide",
          v.names = c('precision', 'bias')) %>%
  select(c("group", all_of(aux0))) %>%
  kable(col.names = c(label(data$group), 
                      rep(c("Precision", "Bias"), length(levels(data$session)))), 
        row.names = FALSE, booktabs = TRUE, escape = FALSE,
        caption = "Bias and precision by group and session using the mixture model.",
        digits = digits) %>%
  add_header_above(c(" " = 1, aux)) %>%
  kable_styling(latex_options = "HOLD_position", 
                bootstrap_options = "striped", full_width = F)
```


```{r fig.cap = 'Bias by group and session using mixture model.', fig.show='hold', out.width = '49%', fig.ncol = 2}
groupedSubjSes %>%
  ggplot(aes(x = time, y = abs(bias), color = group, group = group)) +
  geom_point(alpha = 0.2, show.legend = FALSE,
             position = position_jitterdodge(dodge.width = 0.1, jitter.width = 0.02)) +
  stat_summary(fun.data = "mean_cl_boot",
               position=position_dodge(width=0.1)) +
  stat_summary(fun = mean, geom = "line",  size = 1, show.legend = FALSE,
               position=position_dodge(width=0.1)) +
  # aggregated data by groups:
  #geom_line(data = groupedData, inherit.aes = FALSE, aes(x = time, y = abs(bias), 
  #                                             color = group),linetype = "dashed") +
    scale_color_manual(values=colors) +
  theme(legend.position=c(.7, .8)) +
  labs(x = label(data$time), y = "Bias", color = label(data$group), 
       group = label(data$group))
```


```{r, fig.align='center', message = FALSE, warning = FALSE, fig.height = 3, fig.cap = 'Bias by subject and group through time.'}
groupedSubjSes %>%
  ggplot(aes(x = time, y = abs(bias), color = group, group = subject)) +
  geom_line(alpha = 0.3, show.legend = FALSE) +
  stat_summary(fun.data = "mean_cl_boot", show.legend = FALSE,
               position = position_dodge(width = 0.05), aes(group = group)) +
  stat_summary(fun.y = mean, geom = "line", size = 1, show.legend = FALSE,
               position = position_dodge(width = 0.05), aes(group = group)) +
  # aggregated data by groups:
  # geom_line(data = groupedData, inherit.aes = FALSE, aes(x = time, y = abs(bias), 
  #           color = group), linetype = "dashed", color = 'black') +
  scale_color_manual(values = colors) +
  theme_minimal(base_size = 15) +
  labs(x = label(data$time), y = "Bias", color = label(data$group)) +
  facet_wrap(~ group)
```

```{r }
summary(lme(abs(bias) ~ group * time, random = ~(1)|subject, data = groupedSubjSes))$tTable %>%
  kable(digits = digits, booktabs = TRUE, escape = FALSE,
        caption = 'Linear mixed-effects model where the response is the absolute bias and regressors are group, time and its interaction.') %>%
    kable_styling(latex_options = "HOLD_position", 
                bootstrap_options = "striped", full_width = F)

anova(lme(abs(bias) ~ group * time, random = ~(1)|subject, data = groupedSubjSes)) %>%
  kable(digits = digits, booktabs = TRUE, escape = FALSE,
        caption = "Anova for the linear mixed-effects model where the response is the absolute bias and regressors are group, time and its interaction.") %>%
    kable_styling(latex_options = "HOLD_position", 
                bootstrap_options = "striped", full_width = F)
```

#### Bias using slopes 

```{r fig.show='hold', fig.align='center', fig.cap = 'Coloured lines account for the linear model fitted for bias (subject by subject). Black lines are the results of the linear model fitted on the intercept and slope of the subject-models (coloured lines).'}
bias_mod <- groupedSubjSes %>%
  group_by(subject) %>%
  nest() %>%
  mutate(mod = map(data, function(df) lm(abs(bias) ~ time, data = df)),
         coefficients = map(mod, function(df) df$coefficients),
         intercept = map_dbl(coefficients, 1),
         slope = map_dbl(coefficients, 2), 
         group = substr(subject, 1, 1),
         prediction = map(mod, function(x) predict(x)),
         time = map(data, function(x) x$time))

pred <- expand.grid(group = c('C', 'E', 'S'), time = unique(groupedSubjSes$time))
pred$intercept <- predict(lm(intercept ~ group, data = bias_mod), newdata = pred)
pred$slope <- predict(lm(slope ~ group, data = bias_mod), newdata = pred)
pred <- pred %>%
  mutate(prediction = intercept + slope*time)

bias_mod %>%
  unnest(c(prediction, time)) %>%
  ggplot(aes(x = time, y = prediction, group = subject, color = group)) +
  geom_line(alpha = 0.6) +
  geom_line(data = pred, color = 'black', inherit.aes = FALSE, aes(x = time, y = prediction)) +
  scale_color_manual(values = colors) +
  labs(y = 'Bias') + 
  facet_wrap(~group)
```


```{r}
summary(lm(intercept ~ group,
            data = bias_mod))$coefficients %>%
  kable(digits = digits, booktabs = TRUE, escape = FALSE,
        caption = 'Linear model where the response is the intercept of the linear regression for absolute bias and group is the only regressor.') %>%
    kable_styling(latex_options = "HOLD_position", 
                bootstrap_options = "striped", full_width = F)

summary(lm(slope ~ group,
            data = bias_mod))$coefficients %>%
  kable(digits = digits, booktabs = TRUE, escape = FALSE,
        caption = 'Linear model where the response is the slope of the linear regression for absolute bias and group is the only regressor.') %>%
    kable_styling(latex_options = "HOLD_position", 
                bootstrap_options = "striped", full_width = F)
```

```{r fig.cap = 'Intercept and slope from linear model (fitted by subject) of bias.', fig.show='hold', out.width = '49%', fig.ncol = 2, fig.align='center', warning = FALSE, message = FALSE}
bias_mod %>%
  ggplot(aes(x = group, y = intercept, color = group)) +
  geom_jitter(alpha = 0.4, width = 0.1) +
  stat_summary(fun.data = "mean_cl_normal", show.legend = FALSE,
              aes(group = group), color = 'black') +
  scale_color_manual(values = colors) +
  theme_minimal(base_size = 15) 

bias_mod %>%
  ggplot(aes(x = group, y = slope, color = group)) +
  geom_jitter(alpha = 0.7, width = 0.1) +
  stat_summary(fun.data = "mean_cl_normal", show.legend = FALSE,
              aes(group = group), color = 'black') +
  scale_color_manual(values = colors) +
  theme_minimal(base_size = 15) 
```

### Precision

```{r fig.cap = 'Precision by group and session using mixture model.', fig.show='hold', out.width = '49%', fig.ncol = 2}
groupedSubjSes %>%
  ggplot(aes(x = time, y = precision, color = group, group = group)) +
  geom_point(alpha = 0.2, show.legend = FALSE,
             position = position_jitterdodge(dodge.width = 0.1, jitter.width = 0.02)) +
  stat_summary(fun.data = "mean_cl_boot",
               position=position_dodge(width=0.1)) +
  stat_summary(fun = mean, geom = "line",  size = 1, show.legend = FALSE,
               position=position_dodge(width=0.1)) +
  # aggregated data by groups:
  # geom_line(data = groupedData, inherit.aes = FALSE, aes(x = time, y = precision, 
  #                                               color = group), linetype = "dashed") +
    scale_color_manual(values=colors) +
  theme(legend.position=c(.7, .8)) +
  labs(x = label(data$time), y = "Precision", color = label(data$group), 
       group = label(data$group)) 
```


```{r, fig.align='center', message = FALSE, warning = FALSE, fig.height = 3, fig.cap = 'Precision by subject and group through time.'}
groupedSubjSes %>%
  ggplot(aes(x = time, y = precision, color = group, group = subject)) +
  geom_line(alpha = 0.3, show.legend = FALSE) +
  stat_summary(fun.data = "mean_cl_boot", show.legend = FALSE,
               position = position_dodge(width = 0.05), aes(group = group)) +
  stat_summary(fun = mean, geom = "line", size = 1, show.legend = FALSE,
               position = position_dodge(width = 0.05), aes(group = group)) +
  # aggregated data by groups:
  # geom_line(data = groupedData, inherit.aes = FALSE, aes(x = time, y = precision, 
  #                             color = group), linetype = "dashed", color = 'black') +
  scale_color_manual(values = colors) +
  theme_minimal(base_size = 15) +
  labs(x = label(data$time), y = "Precision", color = label(data$group)) +
  facet_wrap(~ group)
```


```{r}
tryCatch(
  summary(lme(precision ~ group * time, random = ~(1+group)|subject, 
              data = groupedSubjSes))$tTable %>%
  kable(digits = digits, booktabs = TRUE, escape = FALSE,
        caption = 'Linear mixed-effects model where the response is precision and regressors are group, time and its interaction.') %>%
    kable_styling(latex_options = "HOLD_position", 
                bootstrap_options = "striped", full_width = F),
  error = function(i) {
      summary(lm(precision ~ group * time, data = groupedSubjSes))$coefficients %>%
  kable(digits = digits, booktabs = TRUE, escape = FALSE,
        caption = 'Linear model where the response is precision and regressors are group, time and its interaction.') %>%
    kable_styling(latex_options = "HOLD_position", 
                bootstrap_options = "striped", full_width = F)
  })

tryCatch(anova(lme(precision ~ group * time, random = ~(1+group)|subject, data = groupedSubjSes)) %>%
  kable(digits = digits, booktabs = TRUE, escape = FALSE,
        caption = "Anova for the linear mixed-effects model where the response is precision and regressors are group, time and its interaction.") %>%
    kable_styling(latex_options = "HOLD_position", 
                bootstrap_options = "striped", full_width = F),
  error = function(i) {
      anova(lm(precision ~ group * time, data = groupedSubjSes)) %>%
  kable(digits = digits, booktabs = TRUE, escape = FALSE,
        caption = 'Anova of the linear model where the response is precision and regressors are group, time and its interaction.') %>%
    kable_styling(latex_options = "HOLD_position", 
                bootstrap_options = "striped", full_width = F)
  })
```

#### Precision using slopes 

```{r fig.show='hold', fig.align='center', fig.cap = 'Coloured lines account for the linear model fitted for precision (subject by subject). Black lines are the results of the linear model fitted on the intercept and slope of the subject-models (coloured lines).'}
precision_mod <- groupedSubjSes %>%
  group_by(subject) %>%
  nest() %>%
  mutate(mod = map(data, function(df) lm(precision ~ time, data = df)),
         coefficients = map(mod, function(df) df$coefficients),
         intercept = map_dbl(coefficients, 1),
         slope = map_dbl(coefficients, 2), 
         group = substr(subject, 1, 1),
         prediction = map(mod, function(x) predict(x)),
         time = map(data, function(x) x$time))

pred <- expand.grid(group = c('C', 'E', 'S'), time = unique(groupedSubjSes$time))
pred$intercept <- predict(lm(intercept ~ group, data = precision_mod), newdata = pred)
pred$slope <- predict(lm(slope ~ group, data = precision_mod), newdata = pred)
pred <- pred %>%
  mutate(prediction = intercept + slope*time)

precision_mod %>%
  unnest(c(prediction, time)) %>%
  ggplot(aes(x = time, y = prediction, group = subject, color = group)) +
  geom_line(alpha = 0.6) +
  geom_line(data = pred, color = 'black', inherit.aes = FALSE, aes(x = time, y = prediction)) +
  scale_color_manual(values = colors) +
  labs(y = 'Precision') + 
  facet_wrap(~group)
```


```{r}
summary(lm(intercept ~ group,
            data = precision_mod))$coefficients %>%
  kable(digits = digits, booktabs = TRUE, escape = FALSE,
        caption = 'Linear model where the response is the intercept of the linear regression for precision and group is the only regressor.') %>%
    kable_styling(latex_options = "HOLD_position", 
                bootstrap_options = "striped", full_width = F)

summary(lm(slope ~ group,
            data = precision_mod))$coefficients %>%
  kable(digits = digits, booktabs = TRUE, escape = FALSE,
        caption = 'Linear model where the response is the slope of the linear regression for precision and group is the only regressor.') %>%
    kable_styling(latex_options = "HOLD_position", 
                bootstrap_options = "striped", full_width = F)
```

```{r fig.cap = 'Intercept and slope from linear model (fitted by subject) of precision', fig.show='hold', out.width = '49%', fig.ncol = 2, fig.align='center', warning = FALSE, message = FALSE}
precision_mod %>%
  ggplot(aes(x = group, y = intercept, color = group)) +
  geom_jitter(alpha = 0.4, width = 0.1) +
  stat_summary(fun.data = "mean_cl_normal", show.legend = FALSE,
              aes(group = group), color = 'black') +
  scale_color_manual(values = colors) +
  theme_minimal(base_size = 15) 

precision_mod %>%
  ggplot(aes(x = group, y = slope, color = group)) +
  geom_jitter(alpha = 0.7, width = 0.1) +
  stat_summary(fun.data = "mean_cl_normal", show.legend = FALSE,
              aes(group = group), color = 'black') +
  scale_color_manual(values = colors) +
  theme_minimal(base_size = 15) 
```

