---
title: ''
output: html_document
---

```{r include = FALSE}
opts_knit$set(root.dir=normalizePath('../'))
knitr::opts_chunk$set(echo = FALSE, fig.align='center', fig.pos = 'H', message = FALSE, warning = FALSE)
options(knitr.kable.NA = '')
```

```{r}
load("data/preproc_data.RData")
source('helpers/helpers.R')
source('helpers/settings.R')
```

### Bias and precision by group and session
```{r, results = 'asis'}
groupedSubjSes <- data %>%
  group_by(session, subject) %>%
  nest() %>%
  mutate(JV10e = map(.x = data, .f = ~bays_2009_error(X = .x$R_rad, Tg = .x$S_rad)))%>%
  mutate(precision = map_dbl(JV10e, 1), bias = map_dbl(JV10e, 2), 
         group = substr(subject, 1,1), 
         time = unlist(map(data, function(x) unique(x['time'])))) %>%
  select(-c("JV10e")) 

groupedData <- groupedData %>%
  mutate(JV10e = map(.x = data, .f = ~bays_2009_error(X = .x$R_rad, Tg = .x$S_rad)))%>%
  mutate(precision = map_dbl(JV10e, 1), bias = map_dbl(JV10e, 2)) %>%
  select(-c("JV10e"))

aux <- unlist(lapply(levels(data$session), function(x) setNames(2,x)))
aux0 <- apply(expand.grid(c("precision", "bias"), levels(data$session)), 
              1, paste, collapse=".")

groupedData %>%
  select(group, session, precision, bias) %>%
  as.data.frame() %>%
  reshape(idvar = 'group', timevar = 'session', direction = "wide",
          v.names = c('precision', 'bias')) %>%
  select(c("group", all_of(aux0))) %>%
  kable(col.names = c(Hmisc::label(data$group), 
                      rep(c("Precision", "Bias"), length(levels(data$session)))), 
        row.names = FALSE, booktabs = TRUE, escape = FALSE,
        caption = "Bias and precision by group and session.",
        digits = digits) %>%
  add_header_above(c(" " = 1, aux)) %>%
  kable_styling(latex_options = "HOLD_position", 
                bootstrap_options = "striped", full_width = F)
```


```{r fig.cap = 'Bias and precision by group and session.', fig.show='hold', out.width = '49%'}
groupedSubjSes %>%
  ggplot(aes(x = time, y = abs(bias), color = group, group = group)) +
  geom_point(position= position_jitterdodge(jitter.width = 0.01, dodge.width = 0.05), alpha = 0.2) +
  stat_summary(fun.data = "mean_cl_boot", show.legend = FALSE,
               position = position_dodge(width=0.05)) +
  stat_summary(fun = mean, geom = "line", size = 1, show.legend = FALSE,
               position=position_dodge(width=0.05)) +
    scale_color_manual(values=colors) +
  labs(x = Hmisc::label(data$time), y = "Absolute bias", 
       color = Hmisc::label(data$group), group = Hmisc::label(data$group))

groupedSubjSes %>%
  ggplot(aes(x = time, y = precision, color = group, group = group)) +
  geom_point(position= position_jitterdodge(jitter.width = 0.01, dodge.width = 0.05), alpha = 0.2) +
  stat_summary(fun.data = "mean_cl_boot",
               position=position_dodge(width=0.05)) +
  stat_summary(fun = mean, geom = "line",  size = 1, show.legend = FALSE,
               position=position_dodge(width=0.05)) +
    scale_color_manual(values=colors) +
  theme(legend.position=c(.9, .8)) +
  labs(x = Hmisc::label(data$time), y = "Precision", color = Hmisc::label(data$group), 
       group = Hmisc::label(data$group)) 
```

### Bias
```{r, fig.align='center', fig.height = 3, fig.cap = 'Bias by subject and group through time'}
groupedSubjSes %>%
  ggplot(aes(x = time, y = abs(bias), color = group, group = subject)) +
  geom_line(alpha = 0.3, show.legend = FALSE) +
  stat_summary(fun.data = "mean_cl_boot", show.legend = FALSE,
               position = position_dodge(width = 0.05), aes(group = group)) +
  stat_summary(fun = mean, geom = "line", size = 1, show.legend = FALSE,
               position = position_dodge(width = 0.05), aes(group = group)) +
  scale_color_manual(values = colors) +
  theme_minimal(base_size = 15) +
  labs(x = Hmisc::label(data$time), y = "Absolute bias", color = Hmisc::label(data$group)) +
  facet_wrap(~ group)
```

#### Modelling bias

```{r}
summary(lme(precision ~ group * time, random = ~(1+group)|subject, data = groupedSubjSes))$varFix %>%
  kable(digits = digits, booktabs = TRUE, escape = FALSE,
        caption = 'Linear mixed-effects model where the response is precision and regressors are group, time and its interaction.') %>%
    kable_styling(latex_options = "HOLD_position", 
                bootstrap_options = "striped", full_width = F)

anova(lme(precision ~ group * time, random = ~(1+group)|subject, data = groupedSubjSes)) %>%
  kable(digits = digits, booktabs = TRUE, escape = FALSE,
        caption = "Anova for the linear mixed-effects model where the response is precision and regressors are group, time and its interaction.") %>%
    kable_styling(latex_options = "HOLD_position", 
                bootstrap_options = "striped", full_width = F)
```


### Precision

```{r, fig.align='center', fig.height = 3, fig.cap = 'Precision by subject and group through time'}
groupedSubjSes %>%
  ggplot(aes(x = time, y = precision, color = group, group = subject)) +
  geom_line(alpha = 0.3, show.legend = FALSE) +
  stat_summary(fun.data = "mean_cl_boot", show.legend = FALSE,
               position = position_dodge(width = 0.05), aes(group = group)) +
  stat_summary(fun = mean, geom = "line", size = 1, show.legend = FALSE,
               position = position_dodge(width = 0.05), aes(group = group)) +
  scale_color_manual(values = colors) +
  theme_minimal(base_size = 15) +
  labs(x = Hmisc::label(data$time), y = "Precision", color =Hmisc:: label(data$group)) +
  facet_wrap(~ group)
```

#### Modelling precision
```{r }
tryCatch(
  summary(lme(abs(bias) ~ group * time, random = ~(1+group)|subject, data = groupedSubjSes))$varFix %>%
  kable(digits = digits, booktabs = TRUE, escape = FALSE,
        caption = 'Linear mixed-effects model where the response is bias and regressors are group, time and its interaction.') %>%
    kable_styling(latex_options = "HOLD_position", 
                bootstrap_options = "striped", full_width = F),
  error = function(i) {
      summary(lm(abs(bias) ~ group * time, data = groupedSubjSes))$coefficients %>%
  kable(digits = digits, booktabs = TRUE, escape = FALSE,
        caption = 'Linear model where the response is bias and regressors are group, time and its interaction.') %>%
    kable_styling(latex_options = "HOLD_position", 
                bootstrap_options = "striped", full_width = F)
  })

tryCatch(
  anova(lme(abs(bias) ~ group * time, random = ~(1+group)|subject, data = groupedSubjSes)) %>%
    kable(digits = digits, booktabs = TRUE, escape = FALSE,
          caption = 'Anova of a linear mixed-effects model where the response is bias and regressors are group, time and its interaction.') %>%
      kable_styling(latex_options = "HOLD_position", 
                  bootstrap_options = "striped", full_width = F),
  error = function(i) {
      anova(lm(abs(bias) ~ group * time, data = groupedSubjSes)) %>%
  kable(digits = digits, booktabs = TRUE, escape = FALSE,
        caption = 'Anova of the linear model where the response is bias and regressors are group, time and its interaction.') %>%
    kable_styling(latex_options = "HOLD_position", 
                bootstrap_options = "striped", full_width = F)
  })
```

